{
    'name': 'Telesale CRM',
    'version': '19.0.1.0.0',
    'category': 'Telesale/Backend',
    'summary': 'TELESALE CRM',
    'description': """
    """,
    'author': 'Custom',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['web', 'crm', 'asterisk_connector', 'livechat_sidebar'],
    'data': [
        'security/ir.model.access.csv',
        'security/res_group.xml',
        'data/crm_stage.xml',
        'data/lost_reason.xml',
        'wizard/assign_lead.xml',
        'wizard/lost_reason_popup.xml',
        'wizard/schedule_callback.xml',
        'wizard/zalo_chat_wizard.xml',
        'wizard/campaign_assign.xml',
        'views/update_tag.xml',
        'views/crm_lead.xml',
        'views/action_view.xml',
        'views/crm_stage.xml',
        'views/crm_history_assign.xml',
        'views/res_partner.xml',
        'views/crm_lost_reason.xml',
        'views/crm_campaign.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'telesale_crm/static/src/scss/zalo_chat_dialog.scss',
            'telesale_crm/static/src/js/zalo_chat_popup.js',
            'telesale_crm/static/src/js/form_renderer_patch.js',
            'telesale_crm/static/src/xml/zalo_chat_dialog.xml',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
